version: '2.1'
services:
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  services-billing:
    image: mhart/alpine-node:12.16.2
    command: sh -c "node /app/billing.js"
    volumes:
      - ./services:/app 
    depends_on:
      - kafka  
    environment: 
      - KAFKA
      - LOGLEVEL
      - READ_TIMEOUT
  services-notifications:
    image: mhart/alpine-node:12.16.2
    command: sh -c "node /app/notifications.js"
    volumes:
      - ./services:/app 
    depends_on:
      - kafka   
    environment: 
      - KAFKA
      - LOGLEVEL
      - READ_TIMEOUT 
  services-orders:
    image: mhart/alpine-node:12.16.2
    command: sh -c "node /app/orders.js"
    volumes:
      - ./services:/app
    depends_on:
      - kafka    
    environment: 
      - KAFKA
      - LOGLEVEL
      - READ_TIMEOUT 
  services-users:
    image: mhart/alpine-node:12.16.2
    command: sh -c "node /app/users.js"
    volumes:
      - ./services:/app 
    depends_on:
      - kafka   
    environment: 
      - KAFKA
      - LOGLEVEL
      - READ_TIMEOUT 
  nginx:
    image: openresty/openresty:xenial
    command: sh -c "sleep 10 && nginx -g \"daemon off;\""
    ports:
      - "127.0.0.1:${NGINX_EXTERNAL_PORT:-8990}:80"
    depends_on:
      - services-billing
      - services-notifications
      - services-orders
      - services-users
    volumes:
      - ./default.conf:/usr/local/openresty/nginx/conf/conf.d/default.conf
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf  
      