version: '2.1'
services:
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  service-users:
    image: mhart/alpine-node:12.16.2
    command: sh -c "node /app/index.js"
    volumes:
      - ./services/users:/app
    ports:
      - 8080:8080  
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
      